services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rider_api_dev
    volumes:
      - .:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: rider_db_dev
    restart: unless-stopped
    volumes:
      - rider_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  rider_db_data:
