# Generated by Django 5.2.7 on 2025-10-24 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ride', '0002_alter_ride_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'verbose_name': 'Ride', 'verbose_name_plural': 'Rides'},
        ),
        migrations.AlterModelTable(
            name='ride',
            table=None,
        ),
        migrations.CreateModel(
            name='RideEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_events', to='app_ride.ride')),
            ],
            options={
                'verbose_name': 'Ride Event',
                'verbose_name_plural': 'Ride Events',
            },
        ),
    ]
