# Generated by Django 5.2.7 on 2025-10-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ride', '0003_alter_ride_options_alter_ride_table_rideevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('en-route', 'En Route'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], default='en-route', max_length=20),
        ),
    ]
