# Generated by Django 5.2.7 on 2025-10-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ride', '0004_alter_ride_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideevent',
            name='ride',
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
        migrations.DeleteModel(
            name='RideEvent',
        ),
    ]
