# Generated by Django 5.2.7 on 2025-10-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ride', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('en-route', 'En Route'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], default='pending', max_length=20),
        ),
    ]
