# Generated by Django 5.2.7 on 2025-10-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('basic', 'Basic'), ('admin', 'Admin')], default='basic', max_length=20),
        ),
    ]
